name: Feature request
description: Suggest an improvement for Pico REST
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Use case
      description: What would you like to achieve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the desired behaviour.
